### ISSUE TITLE
kenlm这个包一直安装不上

### ISSUE THREAD

**Issue by WLegero** [MgArcher/Text_select_captcha#1]
Collecting https://github.com/kpu/kenlm/archive/master.zip
  Using cached https://github.com/kpu/kenlm/archive/master.zip
Building wheels for collected packages: kenlm
  Building wheel for kenlm (setup.py): started
  Building wheel for kenlm (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'D:\software\Anaconda\envs\conda_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-uoe_q63e\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-uoe_q63e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-k_5ax5yu'
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-uoe_q63e\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'kenlm' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for kenlm
  Running setup.py clean for kenlm
Failed to build kenlm
Installing collected packages: kenlm
    Running setup.py install for kenlm: started
    Running setup.py install for kenlm: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'D:\software\Anaconda\envs\conda_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-uoe_q63e\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-uoe_q63e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-0198um7b\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\software\Anaconda\envs\conda_env\Include\kenlm'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-uoe_q63e\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'kenlm' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\software\Anaconda\envs\conda_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-uoe_q63e\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-uoe_q63e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-0198um7b\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\software\Anaconda\envs\conda_env\Include\kenlm' Check the logs for full command output.

**Comment by 15950552800** [comment]
缺少Microsoft Visual C++ 14.0环境导致的，window安装参考https://www.jianshu.com/p/82d97523adb4

**Comment by yt-xy** [comment]
有MacOS的参考嘛？试了好久还是不行

**Comment by 15950552800** [comment]
买不起mac所以没试过，你可以参考kenlm官网来试试。https://kheafield.com/code/kenlm/

**Comment by yt-xy** [comment]
好的，我再试试，辛苦。
