### ISSUE TITLE
cnn训练

### ISSUE THREAD

**Issue by guowhite** [MgArcher/Text_select_captcha#11]
请问下，cnn文字的训练应该是迁移学习的吧，我尝试直接训练会有过拟合的问题，但是我找不到对应可以做迁移的模型

**Comment by MgArcher** [comment]
是的。 因为文字图片数量过少，不能直接训练的。迁移的模型是别人提供的，不能公开出来。你可以尝试寻找手写字体识别的模型或准备更多的样本数据。

**Comment by guowhite** [comment]
好的明白了，感谢你的回复
