### ISSUE TITLE
在B站上弄了几张验证码图片，总是少识别一两个字

### ISSUE THREAD

**Issue by ancue** [MgArcher/Text_select_captcha#21]
有些字还是框不出来

**Comment by MgArcher** [comment]
你可以把图片发出来

**Comment by yanguangtao** [comment]
![test](https://user-images.githubusercontent.com/4060846/120425053-205bc180-c3a0-11eb-90ff-285b13617e13.jpg)

**Comment by MgArcher** [comment]
极验推出了新版了，原有的代码无法识别，新版本在开发中！
