### ISSUE TITLE
极验的识别不出

### ISSUE THREAD

**Issue by chenwenfeng** [MgArcher/Text_select_captcha#26]
大佬啥时候更新阿

**Comment by dlb-shy** [comment]
验证码更新了，需要自己训练

**Comment by MgArcher** [comment]
看看最近忙不忙吧，新版考虑使用全新的方式来进行识别

**Comment by MgArcher** [comment]
更新了 可以识别最新版了

**Comment by PeelSign** [comment]
貌似不能识别出具体汉字

**Comment by MgArcher** [comment]
新版本不会对具体文字进行识别



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月25日 22:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [MgArcher/Text_select_captcha] 极验的识别不出 (Issue #26) |

貌似不能识别出具体汉字
