### ISSUE TITLE
大佬没有linux环境的decryption依赖

### ISSUE THREAD

**Issue by muxifn** [MgArcher/Text_select_captcha#41]
大佬有了fastapi 部署上docker 发现 load.cp38-win_amd64.pyd 没有liunx的编译文件~~

**Comment by muxifn** [comment]
![image](https://github.com/MgArcher/Text_select_captcha/assets/138860013/f5f8462e-e7e4-4489-8986-59cb157fa290)
好我直接做了一波曲线救国的方式解决了

**Comment by Mayfly777w** [comment]
这个方法貌似在最新版不适用了？有什么别的办法可以在linux上运行吗？

**Comment by Mayfly777w** [comment]
> ![image](https://private-user-images.githubusercontent.com/138860013/261912375-f5f8462e-e7e4-4489-8986-59cb157fa290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5ODIyNTQsIm5iZiI6MTczMjk4MTk1NCwicGF0aCI6Ii8xMzg4NjAwMTMvMjYxOTEyMzc1LWY1Zjg0NjJlLWU3ZTQtNDQ4OS04OTg2LTU5Y2IxNTdmYTI5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxNTUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDAxMTI4NjQ3YzEyMmUzZGY4OTQwNDRhNjU5NTIyNmU1ZDdhMDM0ZWU5MzA5M2NiOWYzZWY2ODkwZTkzYmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aUCUkvfu7awYEJ5_8rfX364bmQqwHCKOSTL090NM_Bk) 好我直接做了一波曲线救国的方式解决了

你是自己训练了模型去用吗？
