### ISSUE TITLE
接口文档报错

### ISSUE THREAD

**Issue by chenyig001** [MgArcher/Text_select_captcha#42]
![image](https://github.com/MgArcher/Text_select_captcha/assets/56058920/1331e110-58c5-49ad-b8b4-187d7fd235b6)

**Comment by muxifn** [comment]
改源码 docs_url=None, redoc_url=None 给这两个去掉

**Comment by MgArcher** [comment]
能否详细描述下报错？

**Comment by MgArcher** [comment]
此问题新版本已解决
