### ISSUE TITLE
信息泄露？

### ISSUE THREAD

**Issue by Zhu-HH** [MgArcher/Text_select_captcha#49]
本地drawing.py内存在铭感信息，还是瞎写的。。。。提醒一下

**Comment by MgArcher** [comment]
只是测试数据，已经删除 感谢提醒



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月07日 16:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [MgArcher/Text_select_captcha] 信息泄露？ (Issue #49) |

本地drawing.py内存在铭感信息，还是瞎写的。。。。提醒一下
