### ISSUE TITLE
people_chars_lm.klm训练集读取失败

### ISSUE THREAD

**Issue by A-dying-ape** [MgArcher/Text_select_captcha#5]
Traceback (most recent call last):
  File "kenlm.pyx", line 139, in kenlm.Model.__init__
RuntimeError: util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'.
No such file or directory while opening F:\系统爬虫学习\图片识别\model\people_chars_lm.klm

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:/系统爬虫学习/图片识别/model_two.py", line 11, in <module>
    from src import word_order
  File "F:\系统爬虫学习\图片识别\src\word_order.py", line 35, in <module>
    model = kenlm.LanguageModel(kenlm_opt.model_path)
  File "kenlm.pyx", line 142, in kenlm.Model.__init__
OSError: Cannot read model 'model/people_chars_lm.klm' (util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'. No such file or directory while opening F:\系统爬虫学习\图片识别\model\people_chars_lm.klm)
model_two 读取people_chars_lm.klm没有找到路径，但是我路径没错呀，大佬帮忙看一下

**Comment by MgArcher** [comment]
换成绝对路径试试呢

**Comment by guofengming11** [comment]
> Traceback (most recent call last):
> File "kenlm.pyx", line 139, in kenlm.Model.**init**
> RuntimeError: util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'.
> No such file or directory while opening F:\系统爬虫学习\图片识别\model\people_chars_lm.klm
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "F:/系统爬虫学习/图片识别/model_two.py", line 11, in
> from src import word_order
> File "F:\系统爬虫学习\图片识别\src\word_order.py", line 35, in
> model = kenlm.LanguageModel(kenlm_opt.model_path)
> File "kenlm.pyx", line 142, in kenlm.Model.**init**
> OSError: Cannot read model 'model/people_chars_lm.klm' (util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'. No such file or directory while opening F:\系统爬虫学习\图片识别\model\people_chars_lm.klm)
> model_two 读取people_chars_lm.klm没有找到路径，但是我路径没错呀，大佬帮忙看一下

请问这个问题您解决了么？我也遇到了同样问题

**Comment by A-dying-ape** [comment]
你怎么找到我的？
可以留个联系方式



---原始邮件---
发件人: "guofengming11"<notifications@github.com&gt;
发送时间: 2020年12月10日(周四) 晚上7:36
收件人: "MgArcher/Text_select_captcha"<Text_select_captcha@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"A-dying-ape"<1416711259@qq.com&gt;;
主题: Re: [MgArcher/Text_select_captcha] people_chars_lm.klm训练集读取失败 (#5)




  
Traceback (most recent call last):
 File "kenlm.pyx", line 139, in kenlm.Model.init
 RuntimeError: util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'.
 No such file or directory while opening F:\系统爬虫学习\图片识别\model\people_chars_lm.klm
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
 File "F:/系统爬虫学习/图片识别/model_two.py", line 11, in
 from src import word_order
 File "F:\系统爬虫学习\图片识别\src\word_order.py", line 35, in
 model = kenlm.LanguageModel(kenlm_opt.model_path)
 File "kenlm.pyx", line 142, in kenlm.Model.init
 OSError: Cannot read model 'model/people_chars_lm.klm' (util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'. No such file or directory while opening F:\系统爬虫学习\图片识别\model\people_chars_lm.klm)
 model_two 读取people_chars_lm.klm没有找到路径，但是我路径没错呀，大佬帮忙看一下
  
请问这个问题您解决了么？我也遇到了同样问题

**Comment by calebgithub** [comment]
你看一下你的路径是不是有正文，有中文的话会有问题的，换到纯英文的路径就行了
