### ISSUE TITLE
作者，可以传一份训练集学习一下吗

### ISSUE THREAD

**Issue by xiaotiananan** [MgArcher/Text_select_captcha#6]

**Comment by MgArcher** [comment]
训练集已经上传至百度网盘
链接：https://pan.baidu.com/s/1FF6A-YZAE1Bofgswp-D29w
提取码：ceow

**Comment by xiaotiananan** [comment]
谢谢老哥







------------------ 原始邮件 ------------------
发件人: 于佳 <notifications@github.com&gt;
发送时间: 2020年10月29日 10:09
收件人: MgArcher/Text_select_captcha <Text_select_captcha@noreply.github.com&gt;
抄送: xiaotiananan <745161427@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[MgArcher/Text_select_captcha] 作者，可以传一份训练集学习一下吗 (#6)





 
训练集已经上传至百度网盘
 链接：https://pan.baidu.com/s/1FF6A-YZAE1Bofgswp-D29w
 提取码：ceow

**Comment by Shinelj** [comment]
> _未提供说明。_

怎么进行训练啊，原谅我是初学者
