### ISSUE TITLE
想请教一下排序是怎么排出来的

### ISSUE THREAD

**Issue by IcyFeather233** [MgArcher/Text_select_captcha#61]
> 因此，本项目采用了图片匹配模型，使用 Siamese 孪生网络对需要点击的字与预先准备好的字库中的字进行匹配，找到最佳匹配的字，并按照一定的规则进行排序。Siamese 孪生网络在图像匹配方面表现优异，能够有效地提高排序的准确性和稳定性。

想问一下这里“一定的规则”是什么样的呢

因为我发现有时候字能检测出但是顺序不对，想看看有没有更好的优化方法

**Comment by MgArcher** [comment]
由孪生网络给出各个图片的相似概率，根据概率排序

**Comment by IcyFeather233** [comment]
我这边比较好奇的地方是，
![image](https://github.com/user-attachments/assets/452ec11b-75f1-4c07-bc3c-955e314a4b09)
比如这个图，模型把上下的“面”“筋”分别配对了，然后怎么知道先点“面”还是先点“筋”呢

**Comment by MgArcher** [comment]
/src/utils/matchingMode.py 中的 find_overall_index函数完成点击顺序的排序

**Comment by IcyFeather233** [comment]
非常感谢大佬答疑~
