### ISSUE TITLE
识别不准

### ISSUE THREAD

**Issue by yangkun1201** [MgArcher/Text_select_captcha#62]
为何bilibili中的验证码识别比较准，其他网站识别的不准
![image](https://github.com/user-attachments/assets/b95240e6-31aa-44a3-9fb5-aa75c572763e)

**Comment by MgArcher** [comment]
因为只对bb站的网站做了训练



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月14日 21:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [MgArcher/Text_select_captcha] 识别不准 (Issue #62) |

为何bilibili中的验证码识别比较准，其他网站识别的不准
image.png (view on web)
