### ISSUE TITLE
 import demo  ModuleNotFoundError: No module named 'demo'

### ISSUE THREAD

**Issue by xiaoqiangruc** [MgArcher/Text_select_captcha#7]
按要求版本，安装了numpy==1.18.5
torch==1.5.1
torchvision==0.6.1
tensorboard==1.14.0
matplotlib==3.3.0
pillow==7.2.0
selenium==3.141.0
requests==2.24.0
kenlm
这些库；
模型也已下载存放到Text_select_captcha-master\model 文件夹

试运行bilbil.py 发现报错      import demo  ModuleNotFoundError: No module named 'demo'
请问是什么原因呢？

**Comment by MgArcher** [comment]
代码已经修改 你可以重新拉
