### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by guowhite** [MgArcher/Text_select_captcha#9]
请教一下 在预测时crnn读取模型 crnn.load_weights(crnn_opt.ocrModel)显存不足，换成了load_state_dict但 计算结果时显存依然内存溢出，我是8G的显存，该怎么处理呢

**Comment by guowhite** [comment]
orientation.py的location_predict函数 input_imgs = Variable(input_imgs.type(Tensor))显存溢出

**Comment by MgArcher** [comment]
8g的显存不会造成溢出的 你可以把相关的报错信息发一下

**Comment by guowhite** [comment]
报错信息在内网的机子发不了，后来用cpu可以了。现在就是用torch官方提供的训练代码训练出的pt模型替换掉旧的模型画不出框，目前还正在修改

**Comment by MgArcher** [comment]
那就不是很清楚了  但是8g的显存是可以跑这个模型的

**Comment by guowhite** [comment]
好的 感谢解答 我这边再尝试修改下

**Comment by guowhite** [comment]
想请教一下，这边用的yolov3的训练代码也是用官方提供的吗，我用官方提供训练出来的模型替换后运行，存在很多问题 -_-

**Comment by MgArcher** [comment]
是的 就是用那份代码训练出来的

**Comment by guowhite** [comment]
-_- 好的感谢
